export const airPortList = [
  { name: 'Malang (MLG)', city: 'Malang' },
  { name: 'Solo (SOC)', city: 'Solo' },
  { name: 'Padang Sidempuan (AEG)', city: 'Padang Sidempuan' },
  { name: 'Semarang (SRG)', city: 'Semarang' },
  { name: 'Denpasar (WADD)', city: 'Denpasar' },
  { name: 'Banyuwangi (BWX)', city: 'Banyuwangi' },
  { name: 'Bario (BBN)', city: 'Bario' },
  { name: 'Luwuk (LUW)', city: 'Luwuk' },
  { name: 'Bunyu (BYQ)', city: 'Bunyu' },
  { name: 'Kupang (KOE)', city: 'Kupang' },
  { name: 'Bengkulu (BKS)', city: 'Bengkulu' },
  { name: 'Biak (BIK)', city: 'Biak' },
  { name: 'Tanjung Pandan (TJQ)', city: 'Tanjung Pandan' },
  { name: 'Jakarta (HLP)', city: 'Jakarta' },
  { name: 'Biak (BJK)', city: 'Biak' },
  { name: 'Batam (BTH)', city: 'Batam' },
  { name: 'Banjarmasin (BJM)', city: 'Banjarmasin' },
  { name: 'Bandung (BDO)', city: 'Bandung' },
  { name: 'Pangkalan Bun (PKN)', city: 'Pangkalan Bun' },
  { name: 'Kaimana (KNG)', city: 'Kaimana' },
  { name: 'Surabaya (SUB)', city: 'Surabaya' },
  { name: 'Majalengka (KJT)', city: 'Majalengka' },
  { name: 'Medan (KNO)', city: 'Medan' },
  { name: 'Lombok (LOP)', city: 'Lombok' },
  { name: 'Sabang (SBG)', city: 'Sabang' },
  { name: 'Alor (ARD)', city: 'Alor' },
  { name: 'Obano (OBD)', city: 'Obano' },
  { name: 'Langgur (LUV)', city: 'Langgur' },
  { name: 'Palu (PLW)', city: 'Palu' },
  { name: 'Nabire (NBX)', city: 'Nabire' },
  { name: 'Badung (DPS)', city: 'Badung' },
  { name: 'Nunukan (NNX)', city: 'Nunukan' },
  { name: 'Labuha (LAH)', city: 'Labuha' },
  { name: 'Pomala (PUM)', city: 'Pomala' },
  { name: 'Ranai (NTX)', city: 'Ranai' },
  { name: 'Manokwari (MKW)', city: 'Manokwari' },
  { name: 'Manado (MDC)', city: 'Manado' },
  { name: 'Jayapura (DJJ)', city: 'Jayapura' },
  { name: 'Balikpapan (BPN)', city: 'Balikpapan' },
  { name: 'Sintang (SQG)', city: 'Sintang' },
  { name: 'Tangerang (CGK)', city: 'Tangerang' },
  { name: 'Soroako (SQR)', city: 'Soroako' },
  { name: 'Bintuni (NTI)', city: 'Bintuni' },
  { name: 'Alor Setar (AOR)', city: 'Alor Setar' },
  { name: 'Ambon (AMQ)', city: 'Ambon' },
  { name: 'Gorontalo (GTO)', city: 'Gorontalo' },
  { name: 'Toli Toli (TLI)', city: 'Toli Toli' },
  { name: 'Ternate (TTE)', city: 'Ternate' },
  { name: 'Tanjung Selor (TSY)', city: 'Tanjung Selor' },
  { name: 'Makassar (UPG)', city: 'Makassar' },
  { name: 'Banda Aceh (BTJ)', city: 'Banda Aceh' },
  { name: 'Kota Bharu (KBR)', city: 'Kota Bharu' },
  { name: 'Pangkal Pinang (PGK)', city: 'Pangkal Pinang' },
  { name: 'Palembang (PLM)', city: 'Palembang' },
  { name: 'Pekanbaru (PKU)', city: 'Pekanbaru' },
  { name: 'Sampit (SMQ)', city: 'Sampit' },
  { name: 'Jambi (DJB)', city: 'Jambi' },
  { name: 'Sumbawa Besar (SWQ)', city: 'Sumbawa Besar' },
  { name: 'Pontianak (PNK)', city: 'Pontianak' },
  { name: 'Senopi (ZEG)', city: 'Senopi' },
  { name: 'Raja Ampat (SIQ)', city: 'Raja Ampat' },
  { name: 'Banjarmasin (BDJ)', city: 'Banjarmasin' },
  { name: 'Padang (PDG)', city: 'Padang' },
  { name: 'Taliabu (TAX)', city: 'Taliabu' },
  { name: 'Tambolaka (TMC)', city: 'Tambolaka' },
  { name: 'Tanah Grogot (TNB)', city: 'Tanah Grogot' },
  { name: 'Tanah Laut (TBT)', city: 'Tanah Laut' },
  { name: 'Tanah Merah (TMH)', city: 'Tanah Merah' },
  { name: 'Tanjung Balai (TJB)', city: 'Tanjung Balai' },
  { name: 'Bandar Lampung (TKG)', city: 'Bandar Lampung' },
  { name: 'Tanjung Pinang (TNJ)', city: 'Tanjung Pinang' },
  { name: 'Tanjung Redeb (BEJ)', city: 'Tanjung Redeb' },
  { name: 'Tarakan (TRK)', city: 'Tarakan' },
  { name: 'Natuna (MWK)', city: 'Natuna' },
  { name: 'Taroena (NAF)', city: 'Taroena' },
  { name: 'Palangkaraya (PKY)', city: 'Palangkaraya' },
];
