export const airPortList = [
  { name: 'Banjarmasin (BDJ)', city: 'Banjarmasin' },
  { name: 'Batam (BTH)', city: 'Batam' },
  { name: 'Bengkulu (BKS)', city: 'Bengkulu' },
  { name: 'Berau (BEJ)', city: 'Berau' },
  { name: 'Denpasar (DPS)', city: 'Denpasar' },
  { name: 'Jakarta (CGK)', city: 'Jakarta' },
  { name: 'Jambi (DJB)', city: 'Jambi' },
  { name: 'Malang (MLG)', city: 'Malang' },
  { name: 'Manado (MDC)', city: 'Manado' },
  { name: 'Padang (PDG)', city: 'Padang' },
  { name: 'Palangkaraya (PKY)', city: 'Palangkaraya' },
  { name: 'Palembang (PLM)', city: 'Palembang' },
  { name: 'Pangkal Pinang (PGK)', city: 'Pangkal Pinang' },
  { name: 'Pekanbaru (PKU)', city: 'Pekanbaru' },
  { name: 'Pontianak (PNK)', city: 'Pontianak' },
  { name: 'Samarinda (AAP)', city: 'Samarinda' },
  { name: 'Semarang (SRG)', city: 'Semarang' },
  { name: 'Silangit (DTB)', city: 'Silangit' },
  { name: 'Surabaya (SUB)', city: 'Surabaya' },
  { name: 'Tarakan (TRK)', city: 'Tarakan' },
  { name: 'Ujung Pandang (UPG)', city: 'Ujung Pandang' },
  { name: 'Yogyakarta (YIA)', city: 'Yogyakarta' },
  { name: 'Medan (KNO)', city: 'Medan' },
  { name: 'Lampung (TKG)', city: 'Lampung' },
];
